name: Deploy to GitHub
on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Compile grammar
        run: npm run generate
      - name: Build WASM binary
        run: npm run build-wasm
      - name: Set up folder for GitHub Pages deployment
        run: |
          mkdir public
          cp tree-sitter-formula.wasm public/tree-sitter-parser.wasm
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
